### ISSUE TITLE
download image file

### ISSUE THREAD

**Issue by jburel** [ome/omero-insight#110]
https://forum.image.sc/t/omero-plugin-to-fiji-not-working/34076/12
```
"loci.formats.FormatException: omero.ApiUsageException
serverStackTrace = “ome.conditions.ApiUsageException: Converting Long 5064622080 to Integer is an overflow.”

```
The issue might be opened in  an other repository after investigation

**Comment by jburel** [comment]
The problem is due to the way we invoke the BF plugin
We request the full plane instead of tiles

**Comment by jburel** [comment]
see https://github.com/ome/bioformats/issues/3508

**Comment by jburel** [comment]
https://github.com/ome/omero-insight/pull/114

**Comment by dominikl** [comment]
Issue could be closed, right?
