### ISSUE TITLE
No enum constant omero.gateway.LoginCredentials.DefaultPort.SSL

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#112]
Just to keep track of https://www.openmicroscopy.org/qa2/qa/feedback/29162/ .
Can't replicate, neither with the `.exe` nor the `.msi` installer.

**Comment by dominikl** [comment]
After working on https://github.com/ome/omero-gateway-java/pull/34 I see now how this happened: Someone entered `ssl://...` as server address. This should be fixed by the mentioned PR and #113 , as the user now gets a proper error message in that case.

**Comment by jburel** [comment]
fixed see https://github.com/ome/omero-insight/pull/113
