### ISSUE TITLE
Improve file attachment dialog

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#117]
Add `*.csv` filter to the file attachment dialog. See https://forum.image.sc/t/adding-a-file-type-to-file-selection-dialog/34879 . On that occassion others (like `*.xls` etc.) could be improved as well. Investigate if it's possible to add a customizable filter.

**Comment by dominikl** [comment]
Solved https://github.com/ome/omero-insight/pull/118

**Comment by jburel** [comment]
included in 5.5.10
