### ISSUE TITLE
Importing jpg images crashes

### ISSUE THREAD

**Issue by CFGrote** [ome/omero-insight#135]
# The short version
* insight import failed during import of metadata
* increasing omero server's jvm heap fixed it

# Suggestion
I experienced an issue when importing images through omero.insight, detailed below. I was able to fix it by increasing the jvm heap size on the server, so no help needed. I just wanted to point out that it took me some time to figure out it was a server issue, not a client issue (first tried increasing insight's heap to no avail). I suggest to make the corresponding error messages more informative and/or make a note in the documentation. This problem will likely occur only on relatively small servers like mine with only 4GB on system RAM.

Since I already drafted this issue while working on the fix, I now don't want to throw it away, so here is the detailed report:

# The details
## The issue
I get the following traceback when importing a single jpeg through omero.insight importer:

```
java.lang.RuntimeException: Failure response on import!
Category: ::omero::grid::ImportRequest
Name: error-on-init
Parameters: {stacktrace=java.lang.OutOfMemoryError: Java heap space
, message=Java heap space}

	at ome.formats.importer.ImportLibrary$ImportCallback.onFinished(ImportLibrary.java:762)
	at omero.cmd.CmdCallbackI.finished(CmdCallbackI.java:334)
	at omero.cmd.CmdCallbackI.poll(CmdCallbackI.java:316)
	at omero.cmd.CmdCallbackI$1.run(CmdCallbackI.java:151)

	at org.openmicroscopy.shoola.env.data.util.Status.update(Status.java:615)
	at ome.formats.importer.ImportLibrary.notifyObservers(ImportLibrary.java:254)
	at ome.formats.importer.ImportLibrary$ImportCallback.onFinished(ImportLibrary.java:768)
	at omero.cmd.CmdCallbackI.finished(CmdCallbackI.java:334)
	at omero.cmd.CmdCallbackI.poll(CmdCallbackI.java:316)
	at omero.cmd.CmdCallbackI$1.run(CmdCallbackI.java:151)
Caused by: java.lang.RuntimeException: Failure response on import!
Category: ::omero::grid::ImportRequest
Name: error-on-init
Parameters: {stacktrace=java.lang.OutOfMemoryError: Java heap space
, message=Java heap space}

	at ome.formats.importer.ImportLibrary$ImportCallback.onFinished(ImportLibrary.java:762)
	... 3 more
```
The import fails during the metadata import: 
![image](https://user-images.githubusercontent.com/15476807/82028025-5c3cbf80-9695-11ea-8a76-70389005259e.png)

On the server, I can locate the image file in `/OMERO/ManagedRepository/...`. The corresponding log has no ERRORS. I found these lines relevant to the metadata import;

```
2020-05-15 09:49:18,123 INFO  [              loci.formats.FormatHandler] (1-thread-5) Populating metadata
2020-05-15 09:49:21,637 DEBUG [                   loci.formats.Memoizer] (1-thread-5) start[1589528958094] time[3543] tag[loci.formats.Memoizer.setId]
2020-05-15 09:49:21,638 INFO  [ o.s.b.r.ManagedImportRequestI.@70b702c1] (1-thread-5) Cancelled
```

## Version and system information:
* omero.insight 5.5.9 for linux 
* debian 10
* java:
```
 $> java -version 
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-1~deb9u1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
```

## What I have tried so far
* Increase heap size in omero.insight shell script: 
```
#DEFAULT_JVM_OPTS='"-Xms256m" "-Xmx1024m" "-Duser.dir=$APP_HOME/"'
DEFAULT_JVM_OPTS='"-Xmx6g" "-Xms256m" "-Duser.dir=$APP_HOME/"'
```
Same problem.

## The fix
* Increased server jvm heap:
```
omero config set omero.jvmcfg.percent 22 # was 15 before this change
```

* Checked new server memory config:
```
$> omero admin jvmcfg
JVM Settings:
============
blitz=-Xmx907m -XX:MaxPermSize=512m -XX:+IgnoreUnrecognizedVMOptions # Settings({'percent': '22', 'strategy': 'percent'})
indexer=-Xmx907m -XX:MaxPermSize=512m -XX:+IgnoreUnrecognizedVMOptions # Settings({'percent': '22', 'strategy': 'percent'})
pixeldata=-Xmx907m -XX:MaxPermSize=512m -XX:+IgnoreUnrecognizedVMOptions # Settings({'percent': '22', 'strategy': 'percent'})
repository=-Xmx907m -XX:MaxPermSize=512m -XX:+IgnoreUnrecognizedVMOptions # Settings({'percent': '22', 'strategy': 'percent'})
```

After a server restart
```
omero admin restart
```
I could successfully import my images.

**Comment by jburel** [comment]
Thanks I can see putting the text into our troubleshooting page.
"insight" just checks the files than be imported it then uploads the files.

**Comment by mtbc** [comment]
Thank you, yes, spotting the OOM in the error and advising the user more specifically could well help many, similarly the server-side diagnostics report could mention when the last OOM was logged. In general OMERO could well benefit from some PRs improving the reporting of various error conditions, e.g., common installation mistakes that prevent the server from starting, and from the clients it can be doubly hard to tell.

**Comment by joshmoore** [comment]
Closing since you've found a workaround, @CFGrote. :+1: for one or more related issues on either docs or perhaps omero-py, @jburel and/or @mtbc, as you see fit.
