### ISSUE TITLE
password imagej log

### ISSUE THREAD

**Issue by jburel** [ome/omero-insight#136]
https://forum.image.sc/t/opening-image-from-omero-in-imagej-creates-log-file-with-plain-text-password/38621

**Comment by dominikl** [comment]
I'm not aware of any change with that respect either. I'll try to find out what's going on there.

**Comment by dominikl** [comment]
Can replicate the issue. Just before the Bioformats import dialog opens, a log window pops up displaying the login credentials. I turned the debug mode on to get some more information (creds replaced by `xxx`):
```
...
UI for displaying ROIS annotations not implemented yet!
Created new BrowseFacility
setKeyUp: -1
location=[OMERO] open=[omero:server=workshop.openmicroscopy.org
user=xxx
port=4064
pass=xxx
groupID=5
iid=49206] view=Hyperstack windowless=false crop=false 
runPlugIn: loci.plugins.LociImporter
runUserPlugIn: loci.plugins.LociImporter, arg=
Bio-Formats: parse core options
Bio-Formats: display option dialogs
Bio-Formats: loci.plugins.in.UpgradeDialog: prompt
Bio-Formats: loci.plugins.in.LocationDialog: skip
Bio-Formats: loci.plugins.in.IdDialog: skip
Bio-Formats: loci.plugins.in.MainDialog: prompt
GenericDialog font: false java.awt.Font[family=Dialog,name=Dialog,style=plain,size=12]
Created new ROIFacility
Created new DataManagerFacility
out> OmeroReader initializing omero:server=workshop.openmicroscopy.org
user=xxx
port=4064
pass=xxx
groupID=5
iid=49206
 
out> OmeroReader.initFile(omero:server=workshop.openmicroscopy.org
user=xxx
port=4064
pass=xxx
groupID=5
iid=49206)
...
```

Maybe it comes from the OmeroReader?

**Comment by joshmoore** [comment]
@jburel @dominikl : https://github.com/ome/omero-insight/blob/master/src/main/java/org/openmicroscopy/shoola/env/ui/TaskBarManager.java#L358 looks to be the culprit:

```
			buffer.append("location=[OMERO] open=[omero:server=");
			buffer.append(lc.getServer().getHost());
			buffer.append("\nuser=");
			buffer.append(lc.getUser().getUsername());
			buffer.append("\nport=");
			buffer.append(lc.getServer().getPort());
			buffer.append("\npass=");
			buffer.append(lc.getUser().getPassword());
			buffer.append("\ngroupID=");
			buffer.append(ctx.getGroupID());
			buffer.append("\niid=");
```

**Comment by jburel** [comment]
I think it is elsewhere that it is written in the log. This is the way to pass info the plugin. I am looking into the problem

**Comment by jburel** [comment]
https://github.com/ome/omero-blitz/blob/master/src/main/java/loci/ome/io/OmeroReader.java#L223 is the source of the problem when using imageJ in debug mode.

**Comment by manerotoni** [comment]
Just a question:
Why is ImageJ seeing the password at all?
ImageJ is calling omero-insight and I hope that omero-insight runs the communication of passwords using a secure and encrypted connection. Somehow the password seems to be exchanged as plain-text.

**Comment by jburel** [comment]
it runs the communication to the server using a secure and encrypted connection.
ImageJ does not need it. I have pushed a fix for review. We will have a new version out as soon as possible

**Comment by jburel** [comment]
https://github.com/ome/omero-insight/pull/137
