### ISSUE TITLE
Fiji: crop image

### ISSUE THREAD

**Issue by jburel** [ome/omero-insight#14]
Saving the image does not work with 5.5.0-m1

**Comment by jburel** [comment]
Tested with the dev version and no problem. Steps followed:
* Connect to OMERO
* Open an Image in IJ
* Draw a rectangle
* Crop the image
* Import the image back to OMERO

cc @pwalczysko

**Comment by pwalczysko** [comment]
>with the dev version 

I took my insight-ij plugin from https://web-proxy.openmicroscopy.org/west-ci/job/OMERO-insight-build/ - how did you get yours ?

**Comment by jburel** [comment]
I tested with both local build and west-ci one.  I cannot repeat the problem
Could the problem come from the version of Fiji you are using?

**Comment by pwalczysko** [comment]
![Screen Shot 2019-04-10 at 12 10 49](https://user-images.githubusercontent.com/2478303/55874241-b5c8e580-5b89-11e9-925e-ed531f7dced8.png)
My Fiji is as above

**Comment by jburel** [comment]
I am using 2.0.0-rc-69/1.52n
Date: 2018-12-04

**Comment by pwalczysko** [comment]
@jburel you have the newest out of us 3 I guess

**Comment by jburel** [comment]
see https://github.com/ome/omero-insight/pull/30
