### ISSUE TITLE
Bug: Import and project selection

### ISSUE THREAD

**Issue by jburel** [ome/omero-insight#148]
* User select an image to import
* Select a project
* "New from folder"
* Import the image
The import is successful, but the "Force Quit" dialog pops up when the user wants to quit

**Comment by pwalczysko** [comment]
I actually can repeat also when no Project is selected. The difference for me is between outreach (bug is present) and demo (bug is not present) servers. Insight 5.5.11 on Mac

**Comment by jburel** [comment]
interesting. i have checking against outreach.

**Comment by jburel** [comment]
``countUploaded`` is not incremented.

**Comment by dominikl** [comment]
Fixed in #149 .
