### ISSUE TITLE
bat file

### ISSUE THREAD

**Issue by jburel** [ome/omero-insight#15]
This is currently not working
See https://github.com/gradle/gradle/issues/1989

**Comment by rgozim** [comment]
Gradle generates it shell/bat scritps from a template file. The template file can either be edited using [Groovy's SimpleTemplateEngine](http://docs.groovy-lang.org/latest/html/documentation/template-engines.html#_simpletemplateengine) or by using a different template file, [as supplied by default ](https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt).

**Comment by rgozim** [comment]
Fix in commit https://github.com/ome/omero-insight/pull/16/commits/8f45c943fa361a85535d26c1d9274750aeb9ff9a

**Comment by jburel** [comment]
Included in https://github.com/ome/omero-insight/releases/tag/v5.5.0-m2
