### ISSUE TITLE
Some scripts don't work in Insight, but work in Web

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#154]
See [29417](https://www.openmicroscopy.org/qa2/qa/feedback/29417/) .

**Comment by dominikl** [comment]
This might be Windows 10 specific. For some reason Insight wants to write the file into some app config directory like `C:\Users\SomeOne\AppData\Local\OMERO.insight\app\config\filesOmero\File_123` . See also [29436](https://www.openmicroscopy.org/qa2/qa/feedback/29436/).

**Comment by jburel** [comment]
not windows specific 
same problem reported at import https://github.com/ome/omero-insight/issues/153

**Comment by dominikl** [comment]
Another one: [29442](https://www.openmicroscopy.org/qa2/qa/feedback/29442/) 
I wonder if that is related to how the Insight application is packaged? I still can't replicate the problem. Have to try with official released packaged on different OS again.
