### ISSUE TITLE
File chooser intermittent error

### ISSUE THREAD

**Issue by jburel** [ome/omero-insight#174]
```
ava.nio.file.InvalidPathException: Illegal char <:> at index 21: C:\OMERO.insight\app\::{F02C1A0D-BE21-4350-88B0-7367FC96EF3C}


	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)


	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)


	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)


	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
```

see https://www.openmicroscopy.org/qa2/qa/feedback/29653/

**Comment by dominikl** [comment]
There are two other very similar issues: #111 and  #146 . And I still don't know how to replicate either of them.

**Comment by dominikl** [comment]
[QA 29996](https://www.openmicroscopy.org/qa2/qa/feedback/29996/)

**Comment by dominikl** [comment]
[QA 30308](https://www.openmicroscopy.org/qa2/qa/feedback/30308/)

**Comment by dominikl** [comment]
[QA 30806](https://www.openmicroscopy.org/qa2/qa/feedback/30806/)

**Comment by dominikl** [comment]
[QA 31223])https://www.openmicroscopy.org/qa2/qa/feedback/31223/

**Comment by jburel** [comment]
Fixed https://github.com/ome/omero-insight/pull/328 (version 5.8.0)
