### ISSUE TITLE
Fiji Windows import image

### ISSUE THREAD

**Issue by pwalczysko** [ome/omero-insight#206]
As confirmed on Win7 and Win10 machines in two separate tests, and also reported by users of recent outreach:

Import on Windows of images using the omero-ij plugin in Fiji does not work:

To repeat,  have a Windows machine and 
  - follow the Crop workflow in https://omero-guides.readthedocs.io/en/latest/fiji/docs/manual_analysis.html#example-2-cropping-and-import
  - after you created the Crop, added to Queue and clicked Import, observe that
  - the Importer, instead of showing 2 blue progress bars as usual is showing "Scanning" message and no progress bars
  - very quickly, the import is highlighted as successfully finished with a green tick in the newly created tab of the importer
  - there is no "View" button though, instead, still the "Scanning" message persists and no blue bars appear
  - the image is not truly imported and cannot be found in OMERO
  - the Fiji log reports that the importer attempted to find the file to import inside a temporary folder as see in the screenshot below
  - but no folder ``AppData`` is in fact present on the machine in question under ``C:\Users\User`` folder as suggested by the Fiji log 

Situation after import
![Failed_2](https://user-images.githubusercontent.com/2478303/109041039-86141f80-76c6-11eb-9659-58187d0c7820.png)
The Fiji log with the path to non-existent folder
![Screenshot 2021-02-24 at 17 02 31](https://user-images.githubusercontent.com/2478303/109041087-92987800-76c6-11eb-95c0-15adad10607c.png)

**Comment by jburel** [comment]
Fixed in https://github.com/ome/omero-insight/pull/207
