### ISSUE TITLE
javax.swing.JComponent: ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#210]
[QA 30043](https://www.openmicroscopy.org/qa2/qa/feedback/30043) (and others). 
```
java.lang.ArrayIndexOutOfBoundsException: No such child: 3
	at java.awt.Container.getComponent(Container.java:336)
	at javax.swing.JComponent.rectangleIsObscured(JComponent.java:4390)
	at javax.swing.JComponent.paint(JComponent.java:1054)
...
```
Gets reported occassionally. Haven't found a way yet to reproduce it. And unfortunately the stacktraces never reveal which Insight component triggers the error.

**Comment by dominikl** [comment]
[QA 30049](https://www.openmicroscopy.org/qa2/qa/feedback/30049/)

**Comment by dominikl** [comment]
[30053](https://www.openmicroscopy.org/qa2/qa/feedback/30053/)

**Comment by dominikl** [comment]
[30067](https://www.openmicroscopy.org/qa2/qa/feedback/30067/) Gettings these a lot now. Still don't know where/how this is triggered.

**Comment by dominikl** [comment]
Maybe the bug is actually older... https://trac.openmicroscopy.org/ome/ticket/7250

**Comment by dominikl** [comment]
[30137](https://www.openmicroscopy.org/qa2/qa/feedback/30137)

**Comment by dominikl** [comment]
[QA 30143](https://www.openmicroscopy.org/qa2/qa/feedback/30143/)

**Comment by dominikl** [comment]
Another one, this time with Java 14: [30157](https://www.openmicroscopy.org/qa2/qa/feedback/30157/)
```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.lang.ArrayIndexOutOfBoundsException: No such child: 3
	at java.desktop/java.awt.Container.getComponent(Container.java:350)
	at java.desktop/javax.swing.JComponent.rectangleIsObscured(JComponent.java:4426)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1072)
...
```

**Comment by jburel** [comment]
see https://www.openmicroscopy.org/qa2/qa/feedback/30244/

**Comment by dominikl** [comment]
[QA 30310](https://www.openmicroscopy.org/qa2/qa/feedback/30310/) Finally with some more information "uploading files to omero". Wonder if it could be related to the overhaul of the Importer (to support 1000+ files). Might have introduced a call to `repaint` outside the UI thread or something like that.

**Comment by dominikl** [comment]
Looks indeed like it's the importer causing the issue: [30314](https://www.openmicroscopy.org/qa2/qa/feedback/30314/) .

**Comment by jburel** [comment]
See also https://www.openmicroscopy.org/qa2/qa/feedback/30325/

**Comment by dominikl** [comment]
[QA 30326](https://www.openmicroscopy.org/qa2/qa/feedback/30326/)

**Comment by jburel** [comment]
The problem is still there see
https://www.openmicroscopy.org/qa2/qa/feedback/30632/

**Comment by dominikl** [comment]
[QA 30664](https://www.openmicroscopy.org/qa2/qa/feedback/30664/) Still looks like it has something to do with the importer code.

**Comment by dominikl** [comment]
I didn't see that Mark already opened an issue for that: https://github.com/ome/omero-insight/issues/162 . I'll close 162 in favour of this one.

**Comment by mtbc** [comment]
The theory I developed back then:

> Perhaps some code is messing with the container's components outside the Swing thread?

Good luck!

**Comment by dominikl** [comment]
Yes, I think so too, and it's has to do with the import components. Initially I thought I introduced it when I overhauled some of the import UI, but then there's already an old trac ticket about it too.

**Comment by jburel** [comment]
See [QA 31016](https://www.openmicroscopy.org/qa2/qa/feedback/31016/) and [QA 31018](https://www.openmicroscopy.org/qa2/qa/feedback/31018/)

**Comment by jburel** [comment]
See https://www.openmicroscopy.org/qa2/qa/feedback/31052/
