### ISSUE TITLE
Download popup "File format" chooser

### ISSUE THREAD

**Issue by pwalczysko** [ome/omero-insight#271]
Download of original file popup shows a dysfunctional dropdown menu saying File format.

Workflow:
1. Start insight
2. Connect to server,
3. Select any image which has original file to it (not inside Plaate, as this might not have the Download enabled on your server)
4. Click onto the Download dropdown in top-right, select the first option, with blue downward facing arrow to dowload the original file
5. Observe that in the bottom of the first dialog (the download location chooser), there is the reduntant "File format" dropdown

![Screenshot 2022-01-14 at 11 45 18](https://user-images.githubusercontent.com/2478303/149510739-ad9076ed-5e80-47d5-af09-00685a3713f6.png)

cc @dominikl @jburel

**Comment by dominikl** [comment]
👍 Thanks Petr. I'll open a separate PR for that, to keep it apart from the current open "download" PR https://github.com/ome/omero-insight/pull/264 .
