### ISSUE TITLE
MDE: required fields not actually required for import

### ISSUE THREAD

**Issue by sebherbert** [ome/omero-insight#304]
Hello,

I've been trying to modify the mdeConfiguration.xml file to support clean imports into our database and ran into the problem that even if some of my fields are set to `required=true`, I can still upload my image without filling out these fields.
I could reproduce the behavior with the "Example Setup: Fields" setup which contains the line
`                <TagDataProp Name="Tag of Type TextField" Unit ="" Visible ="true" Required="true"/>`
Despite this requirement, I could still upload my image without anything in the field.

Could you let me know if I misunderstood something maybe? I'm using OMERO.insight 5.7.0

Cheers,
Sebastien

**Comment by sukunis** [comment]
First of all, I apologise for the late reply!
The function is as follows: when a field is marked as required, a star appears next to the label of the metadata field. In addition, you can select 'show only required' to display only those objects that contain a metadata field marked as required. This allows the user to focus on the most important metadata objects.
This will NOT influence the import in the current version.

Best,
Susanne

**Comment by sebherbert** [comment]
No problem, there was no emergency :) 

Ah ok! The requirement status is only informative but not blocking then!
so it works as expected indeed!

Thanks for the feedback and all the work!

Sebastien
