### ISSUE TITLE
IllegalComponentStateException: component must be showing on the screen

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#313]
[QA 31172](https://www.openmicroscopy.org/qa2/qa/feedback/31172/)
```
java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
	at java.awt.Component.getLocationOnScreen_NoTreeLock(Component.java:2062)
	at java.awt.Component.getLocationOnScreen(Component.java:2036)
	at javax.swing.JPopupMenu.show(JPopupMenu.java:948)
	at org.openmicroscopy.shoola.agents.treeviewer.view.ToolBar.showAvailableScriptsMenu(ToolBar.java:1074)
...
```

There were similar issues in the past: https://github.com/ome/omero-insight/issues/189 , https://github.com/ome/omero-insight/issues/274 .

**Comment by dominikl** [comment]
Argh, looks like I missed one: [31214](https://www.openmicroscopy.org/qa2/qa/feedback/31214/).

**Comment by dominikl** [comment]
[QA 31303](https://www.openmicroscopy.org/qa2/qa/feedback/31303/)

**Comment by dominikl** [comment]
[QA 31309](https://www.openmicroscopy.org/qa2/qa/feedback/31309/)

**Comment by dominikl** [comment]
[QA 31313](https://www.openmicroscopy.org/qa2/qa/feedback/31313/)

**Comment by jburel** [comment]
See https://www.openmicroscopy.org/qa2/qa/feedback/32497/

**Comment by joshmoore** [comment]
[QA 32500](https://www.openmicroscopy.org/qa2/qa/feedback/32500/) as well

**Comment by jburel** [comment]
See also https://www.openmicroscopy.org/qa2/qa/feedback/32547/

**Comment by jburel** [comment]
see also https://www.openmicroscopy.org/qa2/qa/feedback/32550/

**Comment by jburel** [comment]
Fixed in https://github.com/ome/omero-insight/pull/341
