### ISSUE TITLE
OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#316]
For example [QA 31194](https://www.openmicroscopy.org/qa2/qa/feedback/31194/).

Occassionally we'll get these errors reported. I wonder if it's worth to increase the default max heap size to 4GB or something like that. 4GB RAM allocation shouldn't really be an issue nowadays. Your thoughts @jburel ?

**Comment by jburel** [comment]
The default is pretty low see https://github.com/ome/omero-insight/blob/master/buildSrc/src/main/groovy/org/openmicroscopy/InsightBasePlugin.groovy#L56
So we could certainly increase it

**Comment by dominikl** [comment]
Thanks @jburel , opened a PR for it https://github.com/ome/omero-insight/pull/317 .
