### ISSUE TITLE
LDAP issues

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#356]
Like `Cannot find unique user DistinguishedName` [QA 32860](https://www.openmicroscopy.org/qa2/qa/feedback/32860/).
Wonder if Insight could catch these and handle better instead of just crashing.

**Comment by jburel** [comment]
One option will be to parse the stacktrace in insight to handle such case.

**Comment by jburel** [comment]
see https://github.com/ome/omero-insight/pull/393
