### ISSUE TITLE
insight win shortcut

### ISSUE THREAD

**Issue by pwalczysko** [ome/omero-insight#36]
as already discussed with @rgozim , it would be good if there would be a shortcut created on the installation step - the other programmes ask about this when I am trying to install them on Windows (something like : should a shortcut be created on Desktop and or in Start menu ?). Otherwise it is a challenge to find where insight was installed.

cc @jburel 

See discussion on https://github.com/ome/www.openmicroscopy.org/pull/296

**Comment by jburel** [comment]
Replaced by https://github.com/ome/omero-build/issues/27
