### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by scuniff** [ome/omero-insight#401]
Looks lhis code causes an infinite loop

public void remove(String type) {
		this.remove(type);
	}

https://github.com/ome/omero-insight/blob/40566b97d28f9caf5720a55faf15c324a8c6e5de/src/main/java/org/openmicroscopy/shoola/agents/fsimporter/mde/components/ModuleList.java#L67

The code

      this.remove(type)

should be changed to
 
     super.remove(type)

to get to the HashMap.remove() method

**Comment by jburel** [comment]
fixed see https://github.com/ome/omero-insight/pull/402
