### ISSUE TITLE
Return value ignored

### ISSUE THREAD

**Issue by scuniff** [ome/omero-insight#405]
https://github.com/ome/omero-insight/blob/40566b97d28f9caf5720a55faf15c324a8c6e5de/src/main/java/org/openmicroscopy/shoola/util/ui/ColouredButton.java#L176

It doesn’t look like this line of code sets any variable.

	public void setFontIndex(int index)
	{
		getFont().deriveFont(index);
	}

Was this line meant?

`setFont(getFont().deriveFont(index));`

**Comment by jburel** [comment]
https://github.com/ome/omero-insight/pull/407
