### ISSUE TITLE
Is return keyword needed?

### ISSUE THREAD

**Issue by scuniff** [ome/omero-insight#406]
Is return keyword needed?

https://github.com/ome/omero-insight/blob/40566b97d28f9caf5720a55faf15c324a8c6e5de/src/main/java/org/openmicroscopy/shoola/util/roi/io/InputStrategy.java#L510

			if (IOConstants.ATTRIBUTE_DATATYPE_RECTANGLE2D.equals(dataType))
				new Rectangle2D.Double(
				new Double(xValue), new Double(yValue), new Double(widthValue),
				new Double(heightValue));

should be?

			if (IOConstants.ATTRIBUTE_DATATYPE_RECTANGLE2D.equals(dataType))
				return new Rectangle2D.Double(
				new Double(xValue), new Double(yValue), new Double(widthValue),
				new Double(heightValue));

**Comment by jburel** [comment]
https://github.com/ome/omero-insight/pull/408
