### ISSUE TITLE
break statement may be needed

### ISSUE THREAD

**Issue by scuniff** [ome/omero-insight#412]
Regarding:

https://github.com/ome/omero-insight/blob/40566b97d28f9caf5720a55faf15c324a8c6e5de/src/main/java/org/openmicroscopy/shoola/agents/dataBrowser/view/DataBrowserUI.java#L572

			case COLUMNS_VIEW:
				comp = model.getTableView();
			case SEARCH_VIEW:
                            comp = model.getSearchView();

Is break statement needed?

			case COLUMNS_VIEW:
				comp = model.getTableView();
				break;
			case SEARCH_VIEW:
                            comp = model.getSearchView();

**Comment by jburel** [comment]
Fixed https://github.com/ome/omero-insight/pull/413
