### ISSUE TITLE
Logical AND needed

### ISSUE THREAD

**Issue by scuniff** [ome/omero-insight#414]
https://github.com/ome/omero-insight/blob/21b72187f896c36e356dfa6c4c3116bc4b633ba2/src/main/java/org/openmicroscopy/shoola/agents/treeviewer/browser/BrowserControl.java#L328

Regarding the if statement:

                    List<?> l = display.getChildrenDisplay();
                    if (l != null & l.size() > 0) {
                        view.expandNode((TreeImageDisplay) l.get(0), true);
                    }

If variable **l is null** then there will be a NPE when  **l.size()** is executed

I think logical **AND &&** is needed

                    List<?> l = display.getChildrenDisplay();
                    if (l != null && l.size() > 0) {
                        view.expandNode((TreeImageDisplay) l.get(0), true);
                    }

**Comment by jburel** [comment]
Fixed in #419
