### ISSUE TITLE
break statement may be needed in ImViewerControl.java

### ISSUE THREAD

**Issue by scuniff** [ome/omero-insight#415]
https://github.com/ome/omero-insight/blob/21b72187f896c36e356dfa6c4c3116bc4b633ba2/src/main/java/org/openmicroscopy/shoola/agents/imviewer/view/ImViewerControl.java#L905

Is break statement needed in ImViewer.CANCELLED block?

			case ImViewer.CANCELLED:
				window.setVisible(false);
			case ImViewer.LOADING_IMAGE:
				if (historyState == ImViewer.LOADING_METADATA)
					window.setVisible(false);
				view.onStateChange(false);
				window.setVisible(false);
				/*
				window = view.getLoadingWindow();
				if (!window.isVisible())
					UIUtilities.centerAndShow(window);
					*/
				historyState = state;
				break;

Like so?

			case ImViewer.CANCELLED:
				window.setVisible(false);
                            break;
			case ImViewer.LOADING_IMAGE:
				if (historyState == ImViewer.LOADING_METADATA)
					window.setVisible(false);
				view.onStateChange(false);
				window.setVisible(false);
				/*
				window = view.getLoadingWindow();
				if (!window.isVisible())
					UIUtilities.centerAndShow(window);
					*/
				historyState = state;
				break;

**Comment by jburel** [comment]
Fixed in #419
