### ISSUE TITLE
String.equals() should probably be used.

### ISSUE THREAD

**Issue by scuniff** [ome/omero-insight#426]
https://github.com/ome/omero-insight/blob/4e8d0754713b0a3c74908b4ebaa9ebae4e378a14/src/main/java/org/openmicroscopy/shoola/env/ui/TaskBarView.java#L611
line 611:
          
          if (((JMenu) c).getText() == entry.getText()) {

should probably use String.equals(): 

                    if (((JMenu) c).getText().equals(entry.getText()))

like it is at line 597

**Comment by joshmoore** [comment]
:+1:
