### ISSUE TITLE
Review upload/download of artifacts in GHA

### ISSUE THREAD

**Issue by omereleases** [ome/omero-insight#447]
using v4 leads to error

**Comment by sbesson** [comment]
Looking at https://github.com/ome/omero-insight/actions/runs/10884718399, looks like the workflow needs to be updated to match the [breaking changes](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes) in the actions if you want to move to `{upload,download}-artifact@v4`. In particular artifacts are no longer mutable - see also https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#multiple-uploads-to-the-same-named-artifact

**Comment by jburel** [comment]
exactly
I did not have time to look at that now 
@dominikl could you have a look?

**Comment by pwalczysko** [comment]
Possibly fixed by https://github.com/ome/omero-insight/pull/448 - maybe lets wait till next release to close after this :)

**Comment by jburel** [comment]
I think we can close it
