### ISSUE TITLE
Bug: Insight import from root folder

### ISSUE THREAD

**Issue by jburel** [ome/omero-insight#49]
Insight appears to have trouble when importing files that are at the root of a mount if we try to create a new dataset from the local folder name. We have a server exception from a local Windows user at https://www.openmicroscopy.org/qa2/qa/feedback/27121/ (from their home on DIF) and locally on Linux it gives me an NPE.

**Comment by mtbc** [comment]
I think this got fixed. Can try to dig up the PR. Do you remember @dominikl?

**Comment by mtbc** [comment]
Oh sorry, I was remembering the card, I didn't realize this was the same but migrated! Ignore me. :smiley:
