### ISSUE TITLE
Bug: ImageJ plugin 5.5.3 release works only in Fiji

### ISSUE THREAD

**Issue by pwalczysko** [ome/omero-insight#64]
See https://forum.image.sc/t/pb-connectiong-to-omero-with-imagej-but-not-fiji-omero-server-5-5-3/28756

Confirmed the observations from the post (tested on Mac):
ImageJ(downloaded freshly from https://imagej.nih.gov/ij/download.html)

  - 5.5.3 release insight-ij plugin does not work in ImageJ - the menu item OMERO is present, but "Connect to OMERO" does not elicit any action (no obvious error is popping up)
  - 5.4.10 release insight-ij plugin does work in the same ImageJ - Connect to OMERO pops up a splashscreen as expected

Fiji:

  - 5.5.3 release insight-ij plugin works fine
  - 5.4.10 release insight-ij plugin worked fine (tested during outreaches repeatedly)

cc @rgozim @jburel

**Comment by jburel** [comment]
see https://github.com/ome/omero-insight/pull/65
