### ISSUE TITLE
"Export as ome-tiff" option should be disabled for large images

### ISSUE THREAD

**Issue by dominikl** [ome/omero-insight#86]
Large image can't be exported as ome-tiff. The button shoudl be disabled.
See https://www.openmicroscopy.org/qa2/qa/feedback/27969/

**Comment by dominikl** [comment]
Can't reproduce, button is disable for large images.

**Comment by dominikl** [comment]
If I remember correctly the criteria is big image == pyramidal image. If the server reports that the image doesn't need pyramids, but then refuses to export as ome-tiff, then there's not really much to do on the client side; expect hard coding some fixed value to disable the button.
But I can try again to reproduce with a non-default setting just for the record.

**Comment by mtbc** [comment]
I guess, the config service allows the client to ask their values?
