### ISSUE TITLE
handle NPE in deleting objects

### ISSUE THREAD

**Issue by mtbc** [ome/omero-insight#92]
[QA 27988](https://www.openmicroscopy.org/qa2/qa/feedback/27988/) records an NPE. I wonder if the gateway's `delete` returned a `null` callback; is it possible to try to cut no links? Perhaps we can figure out how this happens or handle it better.

**Comment by dominikl** [comment]
I think this is already fixed: https://github.com/ome/omero-insight/pull/67

**Comment by mtbc** [comment]
:+1:
