### ISSUE TITLE
Import wrong dataset

### ISSUE THREAD

**Issue by jburel** [ome/omero-insight#94]
push the "create" button in dataset creation dialog and push of "add to the queue" button are in normal but quick succession:

1. select a dataset, create new dataset A,click import;
2. while import 1 is running: select a dataset, create new dataset B, click import;
3. while import 1 is running: select a dataset, create new dataset C, click import;
After the import:
import 1 and import 2 are imported to dataset A; import 3 is imported to dataset C. Dataset B was created but empty. I had put a log messages to the LocationDialog::getImportSettings method and it seems so, that the LocationDialog doesn't get the right dataset destination if the time between creating a new dataset and add to queue event is very short and the connection to the server is slow

cc @sukunis @dominikl

**Comment by jburel** [comment]
To avoid such situation and the current implementation of client and server
* either we create the object in the swing thread, this means that UI will block until the object is created and returned by the server
* or we do not create the object server-side when the user click ``New... `` The object will be created only when the import process starts similar to "New from folder"

The first option will be the easiest to implement but probably annoying for users when the server is slow

**Comment by dominikl** [comment]
👍 for the first option. A bit a of delay wouldn't be unexpected at least.

**Comment by joshmoore** [comment]
If there are other remote calls currently happening on the swing thread, then the creation of a dataset is unlikely to be an issue. If there _aren't_, then I'd be for trying to keep it that way since we certainly had in the past locked clients where the user had to force kill.

**Comment by jburel** [comment]
there is no remote call on the swing thread, so hopefully the impact will be limited

**Comment by jburel** [comment]
fixed in https://github.com/ome/omero-insight/pull/120

**Comment by jburel** [comment]
https://github.com/ome/omero-insight/pull/121
